# Generated by Django 6.0.2 on 2026-02-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
