# Generated by Django 6.0.2 on 2026-02-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_getintouch_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
