# Generated by Django 6.0.2 on 2026-02-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_getintouch_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
