# Generated by Django 6.0.2 on 2026-02-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_getintouch_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='getintouch',
            name='drivers_license',
            field=models.ImageField(blank=True, null=True, upload_to='drivers_licenses/'),
        ),
    ]
