# Generated by Django 6.0.2 on 2026-02-13 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_getintouch_drivers_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='getintouch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
