# Generated by Django 6.0.2 on 2026-02-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_getintouch_created_at_alter_getintouch_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='drivers_license',
            field=models.ImageField(upload_to='drivers_licenses/'),
        ),
    ]
