# Generated by Django 6.0.2 on 2026-02-15 08:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_getintouch_drivers_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipperRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('origin_city_state', models.CharField(max_length=255)),
                ('destination_city_state', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(choices=[('dry_van', 'Dry Van'), ('flatbed', 'Flatbed'), ('reefer', 'Reefer'), ('po', 'PO (Amazon and US mail)')], default='dry_van', max_length=50)),
                ('estimated_volume', models.CharField(max_length=255)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Shipper/Broker Request',
                'verbose_name_plural': 'Shipper/Broker Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='getintouch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Driver Application', 'verbose_name_plural': 'Driver Applications'},
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='drivers_license',
            field=models.ImageField(help_text="Upload driver's license (max 3MB, JPG/PNG/WEBP/PDF)", upload_to='drivers_licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf'])]),
        ),
    ]
