# Generated by Django 6.0.2 on 2026-02-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_shipperrequest_alter_getintouch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipperrequest',
            name='equipment_type',
            field=models.CharField(choices=[('dry_van', 'Dry Van'), ('flatbed', 'Flatbed'), ('trailer', 'Trailer Type'), ('po', 'PO (Amazon and US mail)')], default='dry_van', max_length=50),
        ),
    ]
