# Generated by Django 6.0.2 on 2026-02-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_shipperrequest_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipperrequest',
            name='equipment_type',
            field=models.CharField(choices=[('dry_van', 'Dry Van'), ('flatbed', 'Flatbed'), ('reefer', 'Reefer'), ('po', 'PO (Amazon and US mail)')], default='dry_van', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipperrequest',
            name='frequency',
            field=models.CharField(help_text='Date range for frequency', max_length=255),
        ),
    ]
